version: "3"

services:
  emqx:
    image: emqx/emqx:latest
    container_name: mqttserver
    volumes:
      - emqx-data:/opt/emqx/data
      - emqx-lib:/opt/emqx/lib
      - ./emqx_auth_username.conf:/opt/emqx/etc/plugins/emqx_auth_username.conf
    ports:
      - 1883:1883
      - 8083:8083
      - 18083:18083
      - 8080:8080
    environment:
      EMQX_ALLOW_ANONYMOUS: "false"
      EMQX_LOADED_PLUGINS: "emqx_recon,emqx_retainer,emqx_management,emqx_dashboard,emqx_auth_username"
    networks:
      - serverhelper
  clientapp:
    image: anton31kah/clientapp:1.0
    networks:
      - serverhelper
    depends_on:
      - emqx

volumes:
  logs:
  emqx-data:
  emqx-lib:

networks:
  serverhelper:
