# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pip install pytest
        pip install pytest-custom_exit_code
        pytest --suppress-no-test-exit-code
    - name: Start mqtt server
      run: |
        sudo docker run -d --name emqx -p 18083:18083 -p 1883:1883 emqx/emqx:latest
    - name: Run the application
      run: |
        sudo docker run --name client_app -p 8000:8000 -d $(sudo docker build -q .)
    - name: Sleep for 5s
      uses: jakejarvis/wait-action@master
      with:
        time: '5s'
    - name: Check the status of the app
      run: |
        curl -s localhost:8000 | grep healthy